spring.application.name=environment
spring.config.import=optional:classpath:influxdb.properties,optional:file:environment/.env[.properties],optional:file:.env[.properties]
spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

kma.service-key=${KMA_API_KEY}
kma.url=https://apihub.kma.go.kr/api/typ02/openApi/VilageFcstInfoService_2.0
kma.location-coordinate-file=classpath:동네예보지점좌표(위경도)_260701.xlsx
