server.port=8765

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE}
spring.data.redis.connect-timeout=3s
spring.data.redis.timeout=3s

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource

spring.datasource.dbcp2.initial-size=5
spring.datasource.dbcp2.min-idle=5
spring.datasource.dbcp2.max-idle=5
spring.datasource.dbcp2.max-total=5

spring.datasource.dbcp2.test-on-borrow=true
spring.datasource.dbcp2.validation-query=SELECT 1
spring.datasource.dbcp2.pool-prepared-statements=true
spring.datasource.dbcp2.max-open-prepared-statements=100
