app.influxdb.url=${INFLUXDB_URL}
app.influxdb.token=${INFLUXDB_TOKEN}
app.influxdb.org=${INFLUXDB_ORG}
app.influxdb.bucket=${INFLUXDB_BUCKET}
app.influxdb.client-type=core-api
app.influxdb.log-level=NONE
app.influxdb.connect-timeout=2s
app.influxdb.read-timeout=10s
app.influxdb.write-timeout=5s
app.influxdb.call-timeout=15s
